name:                harambe
version:             0.1.0.0
github:              "awall/harambe"
license:             BSD3
author:              "Adam Wall"
maintainer:          "agcwall@gmail.com"
copyright:           "2020 Adam Wall"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            RPG with a Gorilla
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/awall/harambe#readme>

dependencies:
- base >= 4.7 && < 5
- lens >= 4.18
- gloss >= 1.13
- GLUT >= 2.1
- OpenGL >= 2.2
- random >= 1.1

default-extensions:
- FlexibleInstances
- ScopedTypeVariables
- TemplateHaskell

executables:
  harambe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints    
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
